services:
  - type: web
    name: nighthack-backend
    runtime: docker
    repo: https://github.com/Siddhram/nighthack.git
    branch: sachin
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        value: sqlite:///./resume_system.db
      - key: DEBUG
        value: "false"
      - key: APP_NAME
        value: Resume Relevance Check System
      - key: PINECONE_API_KEY
        value: pcsk_4B27To_tY2jeLoxqgm97GKUfwxMccU39ZsN3jcd2D8Lq7UjZhjwEyHerwKDc8hpeinqpe
      - key: PINECONE_INDEX_NAME
        value: lang
      - key: PINECONE_ENVIRONMENT
        value: us-east-1
      - key: NOMIC_API_KEY
        value: nk-LeXriqiihZl6pT8TT4QhSB8JQVhmJBAznO6Y-EaaDX4
      - key: GEMINI_API_KEY
        value: AIzaSyCdJtJj4eHmFEGU2iyyiVrwlf4jrH3P45Q
      - key: FRONTEND_URL
        value: https://nighthack-paw6.vercel.app
      - key: ALLOWED_ORIGINS
        value: '["http://localhost:3000", "http://127.0.0.1:3000", "http://localhost:5173", "https://nighthack-ytan.vercel.app", "https://nighthack-ytan.vercel.app/", "https://nighthack-paw6.vercel.app", "https://nighthack-paw6.vercel.app/"]'
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_EXTENSIONS
        value: '["pdf", "docx"]'
      - key: UPLOAD_DIR
        value: uploads
      - key: EMBEDDING_MODEL
        value: nomic-embed-text-v1.5
      - key: LLM_MODEL
        value: gemini-1.5-flash
      - key: SIMILARITY_THRESHOLD
        value: 0.7
      - key: EMBEDDING_DIMENSIONALITY
        value: 256
      - key: CHUNK_SIZE
        value: 500
      - key: CHUNK_OVERLAP
        value: 50
      - key: HARD_MATCH_WEIGHT
        value: 0.4
      - key: SEMANTIC_MATCH_WEIGHT
        value: 0.6
    healthCheckPath: /health
    autoDeploy: true